import { CardDifficulty, LanguageLevel } from '@prisma/client';

export interface RegularVerbData {
  wordOrPhrase: string;
  slug: string;
  transcription: string;
  translation: string;
  level: LanguageLevel;
  difficulty: CardDifficulty;
  frequency: number;
  languageCode: string;
}

export const regularVerbsData: RegularVerbData[] = [
  // A1 Level - Basic Actions
  {
    wordOrPhrase: 'work',
    slug: 'work',
    transcription: 'wɜːk',
    translation: 'работать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'play',
    slug: 'play',
    transcription: 'pleɪ',
    translation: 'играть',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'read',
    slug: 'read',
    transcription: 'riːd',
    translation: 'читать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'write',
    slug: 'write',
    transcription: 'raɪt',
    translation: 'писать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'listen',
    slug: 'listen',
    transcription: 'ˈlɪsən',
    translation: 'слушать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'speak',
    slug: 'speak',
    transcription: 'spiːk',
    translation: 'говорить',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'watch',
    slug: 'watch',
    transcription: 'wɒtʃ',
    translation: 'смотреть',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'open',
    slug: 'open',
    transcription: 'ˈəʊpən',
    translation: 'открывать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'close',
    slug: 'close',
    transcription: 'kləʊz',
    translation: 'закрывать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'start',
    slug: 'start',
    transcription: 'stɑːt',
    translation: 'начинать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'stop',
    slug: 'stop',
    transcription: 'stɒp',
    translation: 'останавливать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'wait',
    slug: 'wait',
    transcription: 'weɪt',
    translation: 'ждать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'live',
    slug: 'live',
    transcription: 'lɪv',
    translation: 'жить',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'study',
    slug: 'study',
    transcription: 'ˈstʌdi',
    translation: 'изучать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'learn',
    slug: 'learn',
    transcription: 'lɜːn',
    translation: 'учиться',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'teach',
    slug: 'teach',
    transcription: 'tiːtʃ',
    translation: 'учить',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'help',
    slug: 'help',
    transcription: 'help',
    translation: 'помогать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'ask',
    slug: 'ask',
    transcription: 'ɑːsk',
    translation: 'спрашивать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'answer',
    slug: 'answer',
    transcription: 'ˈɑːnsə',
    translation: 'отвечать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'call',
    slug: 'call',
    transcription: 'kɔːl',
    translation: 'звонить',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },

  // A2 Level - More Complex Actions
  {
    wordOrPhrase: 'understand',
    slug: 'understand',
    transcription: 'ˌʌndəˈstænd',
    translation: 'понимать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'remember',
    slug: 'remember',
    transcription: 'rɪˈmembə',
    translation: 'помнить',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'forget',
    slug: 'forget',
    transcription: 'fəˈɡet',
    translation: 'забывать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 6,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'think',
    slug: 'think',
    transcription: 'θɪŋk',
    translation: 'думать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 9,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'feel',
    slug: 'feel',
    transcription: 'fiːl',
    translation: 'чувствовать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'believe',
    slug: 'believe',
    transcription: 'bɪˈliːv',
    translation: 'верить',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'hope',
    slug: 'hope',
    transcription: 'həʊp',
    translation: 'надеяться',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'want',
    slug: 'want',
    transcription: 'wɒnt',
    translation: 'хотеть',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 9,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'need',
    slug: 'need',
    transcription: 'niːd',
    translation: 'нуждаться',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'like',
    slug: 'like',
    transcription: 'laɪk',
    translation: 'нравиться',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 9,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'love',
    slug: 'love',
    transcription: 'lʌv',
    translation: 'любить',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'hate',
    slug: 'hate',
    transcription: 'heɪt',
    translation: 'ненавидеть',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 6,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'meet',
    slug: 'meet',
    transcription: 'miːt',
    translation: 'встречать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'show',
    slug: 'show',
    transcription: 'ʃəʊ',
    translation: 'показывать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'give',
    slug: 'give',
    transcription: 'ɡɪv',
    translation: 'давать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'take',
    slug: 'take',
    transcription: 'teɪk',
    translation: 'брать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 8,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'bring',
    slug: 'bring',
    transcription: 'brɪŋ',
    translation: 'приносить',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'send',
    slug: 'send',
    transcription: 'send',
    translation: 'отправлять',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'receive',
    slug: 'receive',
    transcription: 'rɪˈsiːv',
    translation: 'получать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 6,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'explain',
    slug: 'explain',
    transcription: 'ɪkˈspleɪn',
    translation: 'объяснять',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 7,
    languageCode: 'en',
  },
  {
    wordOrPhrase: 'describe',
    slug: 'describe',
    transcription: 'dɪˈskraɪb',
    translation: 'описывать',
    level: 'A2',
    difficulty: 'MEDIUM',
    frequency: 6,
    languageCode: 'en',
  },
];
