# Production configuration
# Используйте: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

name: s4q-prod

services:
  postgres:
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '127.0.0.1:5433:5432' # Только локальный доступ
    volumes:
      - s4q_db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
