export const EnvKeys = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_ACCESS_TOKEN_TTL: 'JWT_ACCESS_TOKEN_TTL',
  JWT_REFRESH_TOKEN_TTL: 'JWT_REFRESH_TOKEN_TTL',
  COOKIE_DOMAIN: 'COOKIE_DOMAIN',
  ALLOWED_ORIGINS: 'ALLOWED_ORIGINS',
} as const
