/**
 * Environment variable keys
 *
 * Centralized constants for environment variable names
 * Used throughout the application for type-safe access to env vars
 *
 * @example
 * // Use in config service
 * const jwtSecret = configService.getOrThrow<string>(EnvKeys.JWT_SECRET);
 */
export const EnvKeys = {
  JWT_SECRET: 'JWT_SECRET',
  JWT_ACCESS_TOKEN_TTL: 'JWT_ACCESS_TOKEN_TTL',
  JWT_REFRESH_TOKEN_TTL: 'JWT_REFRESH_TOKEN_TTL',
  COOKIE_DOMAIN: 'COOKIE_DOMAIN',
  ALLOWED_ORIGINS: 'ALLOWED_ORIGINS',
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  GLOBAL_PREFIX: 'GLOBAL_PREFIX',
  // Email Configuration
  SMTP_HOST: 'SMTP_HOST',
  SMTP_PORT: 'SMTP_PORT',
  SMTP_SECURE: 'SMTP_SECURE',
  SMTP_USER: 'SMTP_USER',
  SMTP_PASS: 'SMTP_PASS',
  EMAIL_FROM: 'EMAIL_FROM',
  EMAIL_REPLY_TO: 'EMAIL_REPLY_TO',
  EMAIL_TEMPLATE_DIR: 'EMAIL_TEMPLATE_DIR',
  // S3 Configuration
  AWS_REGION: 'AWS_REGION',
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  S3_BUCKET_NAME: 'S3_BUCKET_NAME',
  S3_ENDPOINT: 'S3_ENDPOINT',
  S3_MAX_FILE_SIZE: 'S3_MAX_FILE_SIZE',
  S3_ALLOWED_MIME_TYPES: 'S3_ALLOWED_MIME_TYPES',
  // Stripe Configuration
  STRIPE_PUBLISHABLE_KEY: 'STRIPE_PUBLISHABLE_KEY',
  STRIPE_SECRET_KEY: 'STRIPE_SECRET_KEY',
  STRIPE_WEBHOOK_SECRET: 'STRIPE_WEBHOOK_SECRET',
  STRIPE_CURRENCY: 'STRIPE_CURRENCY',
  STRIPE_PAYMENT_METHODS: 'STRIPE_PAYMENT_METHODS',
  STRIPE_DEFAULT_TRIAL_DAYS: 'STRIPE_DEFAULT_TRIAL_DAYS',
  STRIPE_ENABLE_SUBSCRIPTIONS: 'STRIPE_ENABLE_SUBSCRIPTIONS',
  STRIPE_ENABLE_ONE_TIME_PAYMENTS: 'STRIPE_ENABLE_ONE_TIME_PAYMENTS',
  // Telegram Configuration
  TELEGRAM_BOT_TOKEN: 'TELEGRAM_BOT_TOKEN',
  TELEGRAM_BOT_USERNAME: 'TELEGRAM_BOT_USERNAME',
  TELEGRAM_WEBHOOK_URL: 'TELEGRAM_WEBHOOK_URL',
  TELEGRAM_WEBHOOK_SECRET: 'TELEGRAM_WEBHOOK_SECRET',
  TELEGRAM_ENABLE_WEBHOOK: 'TELEGRAM_ENABLE_WEBHOOK',
  TELEGRAM_ENABLE_POLLING: 'TELEGRAM_ENABLE_POLLING',
  TELEGRAM_DEFAULT_PARSE_MODE: 'TELEGRAM_DEFAULT_PARSE_MODE',
  TELEGRAM_ENABLE_NOTIFICATIONS: 'TELEGRAM_ENABLE_NOTIFICATIONS',
  TELEGRAM_ENABLE_COMMANDS: 'TELEGRAM_ENABLE_COMMANDS',
  // Database Configuration
  POSTGRES_URI: 'POSTGRES_URI',
  POSTGRES_SHADOW_URI: 'POSTGRES_SHADOW_URI',
  DB_POOL_MIN: 'DB_POOL_MIN',
  DB_POOL_MAX: 'DB_POOL_MAX',
  DB_IDLE_TIMEOUT: 'DB_IDLE_TIMEOUT',
  DB_CONNECTION_TIMEOUT: 'DB_CONNECTION_TIMEOUT',
  DB_LOGGING_ENABLED: 'DB_LOGGING_ENABLED',
  DB_SLOW_QUERY_THRESHOLD: 'DB_SLOW_QUERY_THRESHOLD',
  DB_SEED_ENABLED: 'DB_SEED_ENABLED',
} as const;
