import { CardDifficulty, LanguageLevel } from '@prisma/client';

export interface AdjectiveData {
  term: string;
  slug: string;
  transcription: string;
  translation: string;
  level: LanguageLevel;
  difficulty: CardDifficulty;
  frequency: number;
  languageCode: string;
}

export const adjectivesData: AdjectiveData[] = [
  // A1 Level - Basic Adjectives
  {
    term: 'big',
    slug: 'big',
    transcription: 'bɪɡ',
    translation: 'большой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'small',
    slug: 'small',
    transcription: 'smɔːl',
    translation: 'маленький',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'good',
    slug: 'good',
    transcription: 'ɡʊd',
    translation: 'хороший',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'bad',
    slug: 'bad',
    transcription: 'bæd',
    translation: 'плохой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'new',
    slug: 'new',
    transcription: 'njuː',
    translation: 'новый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'old',
    slug: 'old',
    transcription: 'əʊld',
    translation: 'старый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'young',
    slug: 'young',
    transcription: 'jʌŋ',
    translation: 'молодой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'hot',
    slug: 'hot',
    transcription: 'hɒt',
    translation: 'горячий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'cold',
    slug: 'cold',
    transcription: 'kəʊld',
    translation: 'холодный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'warm',
    slug: 'warm',
    transcription: 'wɔːm',
    translation: 'теплый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'long',
    slug: 'long',
    transcription: 'lɒŋ',
    translation: 'длинный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'short',
    slug: 'short',
    transcription: 'ʃɔːt',
    translation: 'короткий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'high',
    slug: 'high',
    transcription: 'haɪ',
    translation: 'высокий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'low',
    slug: 'low',
    transcription: 'ləʊ',
    translation: 'низкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'fast',
    slug: 'fast',
    transcription: 'fɑːst',
    translation: 'быстрый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'slow',
    slug: 'slow',
    transcription: 'sləʊ',
    translation: 'медленный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'easy',
    slug: 'easy',
    transcription: 'ˈiːzi',
    translation: 'легкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'difficult',
    slug: 'difficult',
    transcription: 'ˈdɪfɪkəlt',
    translation: 'сложный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'happy',
    slug: 'happy',
    transcription: 'ˈhæpi',
    translation: 'счастливый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'sad',
    slug: 'sad',
    transcription: 'sæd',
    translation: 'грустный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'beautiful',
    slug: 'beautiful',
    transcription: 'ˈbjuːtɪfl',
    translation: 'красивый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'ugly',
    slug: 'ugly',
    transcription: 'ˈʌɡli',
    translation: 'уродливый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'clean',
    slug: 'clean',
    transcription: 'kliːn',
    translation: 'чистый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'dirty',
    slug: 'dirty',
    transcription: 'ˈdɜːti',
    translation: 'грязный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'rich',
    slug: 'rich',
    transcription: 'rɪtʃ',
    translation: 'богатый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'poor',
    slug: 'poor',
    transcription: 'pɔː',
    translation: 'бедный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'strong',
    slug: 'strong',
    transcription: 'strɒŋ',
    translation: 'сильный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'weak',
    slug: 'weak',
    transcription: 'wiːk',
    translation: 'слабый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'tall',
    slug: 'tall',
    transcription: 'tɔːl',
    translation: 'высокий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'fat',
    slug: 'fat',
    transcription: 'fæt',
    translation: 'толстый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'thin',
    slug: 'thin',
    transcription: 'θɪn',
    translation: 'худой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'right',
    slug: 'right',
    transcription: 'raɪt',
    translation: 'правильный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'wrong',
    slug: 'wrong',
    transcription: 'rɒŋ',
    translation: 'неправильный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'same',
    slug: 'same',
    transcription: 'seɪm',
    translation: 'одинаковый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'different',
    slug: 'different',
    transcription: 'ˈdɪfrənt',
    translation: 'разный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'open',
    slug: 'open',
    transcription: 'ˈəʊpən',
    translation: 'открытый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'closed',
    slug: 'closed',
    transcription: 'kləʊzd',
    translation: 'закрытый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'full',
    slug: 'full',
    transcription: 'fʊl',
    translation: 'полный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'empty',
    slug: 'empty',
    transcription: 'ˈempti',
    translation: 'пустой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'heavy',
    slug: 'heavy',
    transcription: 'ˈhevi',
    translation: 'тяжелый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'light',
    slug: 'light',
    transcription: 'laɪt',
    translation: 'легкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'dark',
    slug: 'dark',
    transcription: 'dɑːk',
    translation: 'темный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'bright',
    slug: 'bright',
    transcription: 'braɪt',
    translation: 'яркий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'loud',
    slug: 'loud',
    transcription: 'laʊd',
    translation: 'громкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'quiet',
    slug: 'quiet',
    transcription: 'ˈkwaɪət',
    translation: 'тихий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'soft',
    slug: 'soft',
    transcription: 'sɒft',
    translation: 'мягкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'hard',
    slug: 'hard',
    transcription: 'hɑːd',
    translation: 'твердый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'sweet',
    slug: 'sweet',
    transcription: 'swiːt',
    translation: 'сладкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'sour',
    slug: 'sour',
    transcription: 'ˈsaʊə',
    translation: 'кислый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'fresh',
    slug: 'fresh',
    transcription: 'freʃ',
    translation: 'свежий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'dry',
    slug: 'dry',
    transcription: 'draɪ',
    translation: 'сухой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'wet',
    slug: 'wet',
    transcription: 'wet',
    translation: 'мокрый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'smooth',
    slug: 'smooth',
    transcription: 'smuːð',
    translation: 'гладкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'rough',
    slug: 'rough',
    transcription: 'rʌf',
    translation: 'шероховатый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'sharp',
    slug: 'sharp',
    transcription: 'ʃɑːp',
    translation: 'острый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'dull',
    slug: 'dull',
    transcription: 'dʌl',
    translation: 'тупой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 4,
    languageCode: 'en',
  },
  {
    term: 'wide',
    slug: 'wide',
    transcription: 'waɪd',
    translation: 'широкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'narrow',
    slug: 'narrow',
    transcription: 'ˈnærəʊ',
    translation: 'узкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'deep',
    slug: 'deep',
    transcription: 'diːp',
    translation: 'глубокий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'shallow',
    slug: 'shallow',
    transcription: 'ˈʃæləʊ',
    translation: 'мелкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 4,
    languageCode: 'en',
  },
  {
    term: 'thick',
    slug: 'thick',
    transcription: 'θɪk',
    translation: 'толстый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'thin',
    slug: 'thin',
    transcription: 'θɪn',
    translation: 'тонкий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'round',
    slug: 'round',
    transcription: 'raʊnd',
    translation: 'круглый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'square',
    slug: 'square',
    transcription: 'skweə',
    translation: 'квадратный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'straight',
    slug: 'straight',
    transcription: 'streɪt',
    translation: 'прямой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'curved',
    slug: 'curved',
    transcription: 'kɜːvd',
    translation: 'изогнутый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 4,
    languageCode: 'en',
  },
  {
    term: 'flat',
    slug: 'flat',
    transcription: 'flæt',
    translation: 'плоский',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'bent',
    slug: 'bent',
    transcription: 'bent',
    translation: 'согнутый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 4,
    languageCode: 'en',
  },
  {
    term: 'broken',
    slug: 'broken',
    transcription: 'ˈbrəʊkən',
    translation: 'сломанный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'fixed',
    slug: 'fixed',
    transcription: 'fɪkst',
    translation: 'починенный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'ready',
    slug: 'ready',
    transcription: 'ˈredi',
    translation: 'готовый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'busy',
    slug: 'busy',
    transcription: 'ˈbɪzi',
    translation: 'занятый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'free',
    slug: 'free',
    transcription: 'friː',
    translation: 'свободный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'safe',
    slug: 'safe',
    transcription: 'seɪf',
    translation: 'безопасный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'dangerous',
    slug: 'dangerous',
    transcription: 'ˈdeɪndʒərəs',
    translation: 'опасный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'important',
    slug: 'important',
    transcription: 'ɪmˈpɔːtnt',
    translation: 'важный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'special',
    slug: 'special',
    transcription: 'ˈspeʃl',
    translation: 'особенный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'normal',
    slug: 'normal',
    transcription: 'ˈnɔːml',
    translation: 'обычный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'strange',
    slug: 'strange',
    transcription: 'streɪndʒ',
    translation: 'странный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'funny',
    slug: 'funny',
    transcription: 'ˈfʌni',
    translation: 'смешной',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'serious',
    slug: 'serious',
    transcription: 'ˈsɪəriəs',
    translation: 'серьезный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'friendly',
    slug: 'friendly',
    transcription: 'ˈfrendli',
    translation: 'дружелюбный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'kind',
    slug: 'kind',
    transcription: 'kaɪnd',
    translation: 'добрый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'mean',
    slug: 'mean',
    transcription: 'miːn',
    translation: 'злой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'polite',
    slug: 'polite',
    transcription: 'pəˈlaɪt',
    translation: 'вежливый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'rude',
    slug: 'rude',
    transcription: 'ruːd',
    translation: 'грубый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'clever',
    slug: 'clever',
    transcription: 'ˈklevə',
    translation: 'умный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'stupid',
    slug: 'stupid',
    transcription: 'ˈstjuːpɪd',
    translation: 'глупый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'lazy',
    slug: 'lazy',
    transcription: 'ˈleɪzi',
    translation: 'ленивый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'hardworking',
    slug: 'hardworking',
    transcription: 'ˌhɑːdˈwɜːkɪŋ',
    translation: 'трудолюбивый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'brave',
    slug: 'brave',
    transcription: 'breɪv',
    translation: 'храбрый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'scared',
    slug: 'scared',
    transcription: 'skeəd',
    translation: 'испуганный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'excited',
    slug: 'excited',
    transcription: 'ɪkˈsaɪtɪd',
    translation: 'взволнованный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'bored',
    slug: 'bored',
    transcription: 'bɔːd',
    translation: 'скучающий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'tired',
    slug: 'tired',
    transcription: 'ˈtaɪəd',
    translation: 'уставший',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'hungry',
    slug: 'hungry',
    transcription: 'ˈhʌŋɡri',
    translation: 'голодный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'thirsty',
    slug: 'thirsty',
    transcription: 'ˈθɜːsti',
    translation: 'жаждущий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'sick',
    slug: 'sick',
    transcription: 'sɪk',
    translation: 'больной',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'healthy',
    slug: 'healthy',
    transcription: 'ˈhelθi',
    translation: 'здоровый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'married',
    slug: 'married',
    transcription: 'ˈmærid',
    translation: 'женатый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'single',
    slug: 'single',
    transcription: 'ˈsɪŋɡl',
    translation: 'холостой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'pregnant',
    slug: 'pregnant',
    transcription: 'ˈpreɡnənt',
    translation: 'беременная',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 4,
    languageCode: 'en',
  },
  {
    term: 'dead',
    slug: 'dead',
    transcription: 'ded',
    translation: 'мертвый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'alive',
    slug: 'alive',
    transcription: 'əˈlaɪv',
    translation: 'живой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'asleep',
    slug: 'asleep',
    transcription: 'əˈsliːp',
    translation: 'спящий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'awake',
    slug: 'awake',
    transcription: 'əˈweɪk',
    translation: 'бодрствующий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'angry',
    slug: 'angry',
    transcription: 'ˈæŋɡri',
    translation: 'злой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'calm',
    slug: 'calm',
    transcription: 'kɑːm',
    translation: 'спокойный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'nervous',
    slug: 'nervous',
    transcription: 'ˈnɜːvəs',
    translation: 'нервный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'relaxed',
    slug: 'relaxed',
    transcription: 'rɪˈlækst',
    translation: 'расслабленный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'worried',
    slug: 'worried',
    transcription: 'ˈwʌrid',
    translation: 'обеспокоенный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'surprised',
    slug: 'surprised',
    transcription: 'səˈpraɪzd',
    translation: 'удивленный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'confused',
    slug: 'confused',
    transcription: 'kənˈfjuːzd',
    translation: 'запутанный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'interested',
    slug: 'interested',
    transcription: 'ˈɪntrəstɪd',
    translation: 'заинтересованный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'boring',
    slug: 'boring',
    transcription: 'ˈbɔːrɪŋ',
    translation: 'скучный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'interesting',
    slug: 'interesting',
    transcription: 'ˈɪntrəstɪŋ',
    translation: 'интересный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'expensive',
    slug: 'expensive',
    transcription: 'ɪkˈspensɪv',
    translation: 'дорогой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'cheap',
    slug: 'cheap',
    transcription: 'tʃiːp',
    translation: 'дешевый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'free',
    slug: 'free',
    transcription: 'friː',
    translation: 'бесплатный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'paid',
    slug: 'paid',
    transcription: 'peɪd',
    translation: 'оплаченный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'public',
    slug: 'public',
    transcription: 'ˈpʌblɪk',
    translation: 'общественный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'private',
    slug: 'private',
    transcription: 'ˈpraɪvət',
    translation: 'частный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'local',
    slug: 'local',
    transcription: 'ˈləʊkl',
    translation: 'местный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'foreign',
    slug: 'foreign',
    transcription: 'ˈfɒrən',
    translation: 'иностранный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'national',
    slug: 'national',
    transcription: 'ˈnæʃnəl',
    translation: 'национальный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'international',
    slug: 'international',
    transcription: 'ˌɪntəˈnæʃnəl',
    translation: 'международный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'modern',
    slug: 'modern',
    transcription: 'ˈmɒdn',
    translation: 'современный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'traditional',
    slug: 'traditional',
    transcription: 'trəˈdɪʃənl',
    translation: 'традиционный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'famous',
    slug: 'famous',
    transcription: 'ˈfeɪməs',
    translation: 'известный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'popular',
    slug: 'popular',
    transcription: 'ˈpɒpjələ',
    translation: 'популярный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'successful',
    slug: 'successful',
    transcription: 'səkˈsesfl',
    translation: 'успешный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'famous',
    slug: 'famous',
    transcription: 'ˈfeɪməs',
    translation: 'известный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'popular',
    slug: 'popular',
    transcription: 'ˈpɒpjələ',
    translation: 'популярный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'successful',
    slug: 'successful',
    transcription: 'səkˈsesfl',
    translation: 'успешный',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
];
