import { CardDifficulty, LanguageLevel } from '@prisma/client';

export interface AdverbData {
  term: string;
  slug: string;
  transcription: string;
  translation: string;
  level: LanguageLevel;
  difficulty: CardDifficulty;
  frequency: number;
  languageCode: string;
}

export const adverbsData: AdverbData[] = [
  // A1 Level - Basic Adverbs
  {
    term: 'very',
    slug: 'very',
    transcription: 'ˈveri',
    translation: 'очень',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'too',
    slug: 'too',
    transcription: 'tuː',
    translation: 'слишком',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'so',
    slug: 'so',
    transcription: 'səʊ',
    translation: 'так',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'quite',
    slug: 'quite',
    transcription: 'kwaɪt',
    translation: 'довольно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'really',
    slug: 'really',
    transcription: 'ˈrɪəli',
    translation: 'действительно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'well',
    slug: 'well',
    transcription: 'wel',
    translation: 'хорошо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'badly',
    slug: 'badly',
    transcription: 'ˈbædli',
    translation: 'плохо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'fast',
    slug: 'fast',
    transcription: 'fɑːst',
    translation: 'быстро',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'slowly',
    slug: 'slowly',
    transcription: 'ˈsləʊli',
    translation: 'медленно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'quickly',
    slug: 'quickly',
    transcription: 'ˈkwɪkli',
    translation: 'быстро',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'early',
    slug: 'early',
    transcription: 'ˈɜːli',
    translation: 'рано',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'late',
    slug: 'late',
    transcription: 'leɪt',
    translation: 'поздно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'now',
    slug: 'now',
    transcription: 'naʊ',
    translation: 'сейчас',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'then',
    slug: 'then',
    transcription: 'ðen',
    translation: 'тогда',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'today',
    slug: 'today',
    transcription: 'təˈdeɪ',
    translation: 'сегодня',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'yesterday',
    slug: 'yesterday',
    transcription: 'ˈjestədeɪ',
    translation: 'вчера',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'tomorrow',
    slug: 'tomorrow',
    transcription: 'təˈmɒrəʊ',
    translation: 'завтра',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'here',
    slug: 'here',
    transcription: 'hɪə',
    translation: 'здесь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'there',
    slug: 'there',
    transcription: 'ðeə',
    translation: 'там',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'everywhere',
    slug: 'everywhere',
    transcription: 'ˈevriweə',
    translation: 'везде',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'nowhere',
    slug: 'nowhere',
    transcription: 'ˈnəʊweə',
    translation: 'нигде',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'somewhere',
    slug: 'somewhere',
    transcription: 'ˈsʌmweə',
    translation: 'где-то',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'anywhere',
    slug: 'anywhere',
    transcription: 'ˈeniweə',
    translation: 'где-нибудь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'inside',
    slug: 'inside',
    transcription: 'ˌɪnˈsaɪd',
    translation: 'внутри',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'outside',
    slug: 'outside',
    transcription: 'ˌaʊtˈsaɪd',
    translation: 'снаружи',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'upstairs',
    slug: 'upstairs',
    transcription: 'ˌʌpˈsteəz',
    translation: 'наверх',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'downstairs',
    slug: 'downstairs',
    transcription: 'ˌdaʊnˈsteəz',
    translation: 'вниз',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'up',
    slug: 'up',
    transcription: 'ʌp',
    translation: 'вверх',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'down',
    slug: 'down',
    transcription: 'daʊn',
    translation: 'вниз',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'in',
    slug: 'in',
    transcription: 'ɪn',
    translation: 'внутри',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'out',
    slug: 'out',
    transcription: 'aʊt',
    translation: 'наружу',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'on',
    slug: 'on',
    transcription: 'ɒn',
    translation: 'на',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'off',
    slug: 'off',
    transcription: 'ɒf',
    translation: 'выключен',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'over',
    slug: 'over',
    transcription: 'ˈəʊvə',
    translation: 'над',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'under',
    slug: 'under',
    transcription: 'ˈʌndə',
    translation: 'под',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'above',
    slug: 'above',
    transcription: 'əˈbʌv',
    translation: 'выше',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'below',
    slug: 'below',
    transcription: 'bɪˈləʊ',
    translation: 'ниже',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'behind',
    slug: 'behind',
    transcription: 'bɪˈhaɪnd',
    translation: 'за',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'in front of',
    slug: 'in-front-of',
    transcription: 'ɪn frʌnt əv',
    translation: 'перед',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'next to',
    slug: 'next-to',
    transcription: 'nekst tuː',
    translation: 'рядом с',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'near',
    slug: 'near',
    transcription: 'nɪə',
    translation: 'близко',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'far',
    slug: 'far',
    transcription: 'fɑː',
    translation: 'далеко',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'away',
    slug: 'away',
    transcription: 'əˈweɪ',
    translation: 'прочь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'back',
    slug: 'back',
    transcription: 'bæk',
    translation: 'назад',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'forward',
    slug: 'forward',
    transcription: 'ˈfɔːwəd',
    translation: 'вперед',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'left',
    slug: 'left',
    transcription: 'left',
    translation: 'налево',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'right',
    slug: 'right',
    transcription: 'raɪt',
    translation: 'направо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'straight',
    slug: 'straight',
    transcription: 'streɪt',
    translation: 'прямо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'around',
    slug: 'around',
    transcription: 'əˈraʊnd',
    translation: 'вокруг',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'through',
    slug: 'through',
    transcription: 'θruː',
    translation: 'через',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'across',
    slug: 'across',
    transcription: 'əˈkrɒs',
    translation: 'через',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'along',
    slug: 'along',
    transcription: 'əˈlɒŋ',
    translation: 'вдоль',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'together',
    slug: 'together',
    transcription: 'təˈɡeðə',
    translation: 'вместе',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'alone',
    slug: 'alone',
    transcription: 'əˈləʊn',
    translation: 'один',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'with',
    slug: 'with',
    transcription: 'wɪð',
    translation: 'с',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'without',
    slug: 'without',
    transcription: 'wɪˈðaʊt',
    translation: 'без',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'against',
    slug: 'against',
    transcription: 'əˈɡenst',
    translation: 'против',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'for',
    slug: 'for',
    transcription: 'fɔː',
    translation: 'для',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'from',
    slug: 'from',
    transcription: 'frɒm',
    translation: 'от',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'to',
    slug: 'to',
    transcription: 'tuː',
    translation: 'к',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'of',
    slug: 'of',
    transcription: 'ɒv',
    translation: 'из',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'by',
    slug: 'by',
    transcription: 'baɪ',
    translation: 'у',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'about',
    slug: 'about',
    transcription: 'əˈbaʊt',
    translation: 'о',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'like',
    slug: 'like',
    transcription: 'laɪk',
    translation: 'как',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'as',
    slug: 'as',
    transcription: 'æz',
    translation: 'как',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'than',
    slug: 'than',
    transcription: 'ðæn',
    translation: 'чем',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'more',
    slug: 'more',
    transcription: 'mɔː',
    translation: 'больше',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'less',
    slug: 'less',
    transcription: 'les',
    translation: 'меньше',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'most',
    slug: 'most',
    transcription: 'məʊst',
    translation: 'больше всего',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'least',
    slug: 'least',
    transcription: 'liːst',
    translation: 'меньше всего',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'better',
    slug: 'better',
    transcription: 'ˈbetə',
    translation: 'лучше',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'worse',
    slug: 'worse',
    transcription: 'wɜːs',
    translation: 'хуже',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'best',
    slug: 'best',
    transcription: 'best',
    translation: 'лучше всего',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'worst',
    slug: 'worst',
    transcription: 'wɜːst',
    translation: 'хуже всего',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'first',
    slug: 'first',
    transcription: 'fɜːst',
    translation: 'первый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'last',
    slug: 'last',
    transcription: 'lɑːst',
    translation: 'последний',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'next',
    slug: 'next',
    transcription: 'nekst',
    translation: 'следующий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'previous',
    slug: 'previous',
    transcription: 'ˈpriːviəs',
    translation: 'предыдущий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'current',
    slug: 'current',
    transcription: 'ˈkʌrənt',
    translation: 'текущий',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'recent',
    slug: 'recent',
    transcription: 'ˈriːsnt',
    translation: 'недавний',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'old',
    slug: 'old',
    transcription: 'əʊld',
    translation: 'старый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'new',
    slug: 'new',
    transcription: 'njuː',
    translation: 'новый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'young',
    slug: 'young',
    transcription: 'jʌŋ',
    translation: 'молодой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'old',
    slug: 'old',
    transcription: 'əʊld',
    translation: 'старый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'new',
    slug: 'new',
    transcription: 'njuː',
    translation: 'новый',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'young',
    slug: 'young',
    transcription: 'jʌŋ',
    translation: 'молодой',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
];
