import { LanguageLevel, VerbType } from '@prisma/client';

export interface IrregularVerbData {
  infinitive: string;
  pastSimple: string;
  pastParticiple: string;
  translation: string;
  level: LanguageLevel;
  verbType: VerbType;
  frequency: number;
  difficulty: number;
  transcription?: string;
  languageCode: string;
}

export const IRREGULAR_VERBS_DATA: IrregularVerbData[] = [
  // A1 Level - Essential Irregular Verbs
  {
    infinitive: 'be',
    pastSimple: 'was/were',
    pastParticiple: 'been',
    translation: 'быть',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 10,
    difficulty: 3,
    languageCode: 'en',
    transcription: 'biː',
  },
  {
    infinitive: 'have',
    pastSimple: 'had',
    pastParticiple: 'had',
    translation: 'иметь',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 10,
    difficulty: 3,
    languageCode: 'en',
    transcription: 'hæv',
  },
  {
    infinitive: 'do',
    pastSimple: 'did',
    pastParticiple: 'done',
    translation: 'делать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 10,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'duː',
  },
  {
    infinitive: 'go',
    pastSimple: 'went',
    pastParticiple: 'gone',
    translation: 'идти',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'ɡəʊ',
  },
  {
    infinitive: 'come',
    pastSimple: 'came',
    pastParticiple: 'come',
    translation: 'приходить',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'kʌm',
  },
  {
    infinitive: 'see',
    pastSimple: 'saw',
    pastParticiple: 'seen',
    translation: 'видеть',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'siː',
  },
  {
    infinitive: 'hear',
    pastSimple: 'heard',
    pastParticiple: 'heard',
    translation: 'слышать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'hɪə',
  },
  {
    infinitive: 'say',
    pastSimple: 'said',
    pastParticiple: 'said',
    translation: 'говорить',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'seɪ',
  },
  {
    infinitive: 'tell',
    pastSimple: 'told',
    pastParticiple: 'told',
    translation: 'рассказывать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'tel',
  },
  {
    infinitive: 'know',
    pastSimple: 'knew',
    pastParticiple: 'known',
    translation: 'знать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'nəʊ',
  },
  {
    infinitive: 'get',
    pastSimple: 'got',
    pastParticiple: 'got/gotten',
    translation: 'получать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'ɡet',
  },
  {
    infinitive: 'make',
    pastSimple: 'made',
    pastParticiple: 'made',
    translation: 'делать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'meɪk',
  },
  {
    infinitive: 'find',
    pastSimple: 'found',
    pastParticiple: 'found',
    translation: 'находить',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'faɪnd',
  },
  {
    infinitive: 'give',
    pastSimple: 'gave',
    pastParticiple: 'given',
    translation: 'давать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'ɡɪv',
  },
  {
    infinitive: 'take',
    pastSimple: 'took',
    pastParticiple: 'taken',
    translation: 'брать',
    level: 'A1',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'teɪk',
  },

  // A2 Level - More Complex Irregular Verbs
  {
    infinitive: 'think',
    pastSimple: 'thought',
    pastParticiple: 'thought',
    translation: 'думать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'θɪŋk',
  },
  {
    infinitive: 'feel',
    pastSimple: 'felt',
    pastParticiple: 'felt',
    translation: 'чувствовать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'fiːl',
  },
  {
    infinitive: 'become',
    pastSimple: 'became',
    pastParticiple: 'become',
    translation: 'становиться',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'bɪˈkʌm',
  },
  {
    infinitive: 'begin',
    pastSimple: 'began',
    pastParticiple: 'begun',
    translation: 'начинать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'bɪˈɡɪn',
  },
  {
    infinitive: 'break',
    pastSimple: 'broke',
    pastParticiple: 'broken',
    translation: 'ломать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 6,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'breɪk',
  },
  {
    infinitive: 'bring',
    pastSimple: 'brought',
    pastParticiple: 'brought',
    translation: 'приносить',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'brɪŋ',
  },
  {
    infinitive: 'build',
    pastSimple: 'built',
    pastParticiple: 'built',
    translation: 'строить',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 6,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'bɪld',
  },
  {
    infinitive: 'buy',
    pastSimple: 'bought',
    pastParticiple: 'bought',
    translation: 'покупать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'baɪ',
  },
  {
    infinitive: 'catch',
    pastSimple: 'caught',
    pastParticiple: 'caught',
    translation: 'ловить',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 6,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'kætʃ',
  },
  {
    infinitive: 'choose',
    pastSimple: 'chose',
    pastParticiple: 'chosen',
    translation: 'выбирать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'tʃuːz',
  },
  {
    infinitive: 'come',
    pastSimple: 'came',
    pastParticiple: 'come',
    translation: 'приходить',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 9,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'kʌm',
  },
  {
    infinitive: 'cost',
    pastSimple: 'cost',
    pastParticiple: 'cost',
    translation: 'стоить',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 4,
    languageCode: 'en',
    transcription: 'kɒst',
  },
  {
    infinitive: 'cut',
    pastSimple: 'cut',
    pastParticiple: 'cut',
    translation: 'резать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 3,
    languageCode: 'en',
    transcription: 'kʌt',
  },
  {
    infinitive: 'draw',
    pastSimple: 'drew',
    pastParticiple: 'drawn',
    translation: 'рисовать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 6,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'drɔː',
  },
  {
    infinitive: 'drink',
    pastSimple: 'drank',
    pastParticiple: 'drunk',
    translation: 'пить',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'drɪŋk',
  },
  {
    infinitive: 'drive',
    pastSimple: 'drove',
    pastParticiple: 'driven',
    translation: 'водить',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'draɪv',
  },
  {
    infinitive: 'eat',
    pastSimple: 'ate',
    pastParticiple: 'eaten',
    translation: 'есть',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 8,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'iːt',
  },
  {
    infinitive: 'fall',
    pastSimple: 'fell',
    pastParticiple: 'fallen',
    translation: 'падать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 7,
    difficulty: 5,
    languageCode: 'en',
    transcription: 'fɔːl',
  },
  {
    infinitive: 'fight',
    pastSimple: 'fought',
    pastParticiple: 'fought',
    translation: 'бороться',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 5,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'faɪt',
  },
  {
    infinitive: 'fly',
    pastSimple: 'flew',
    pastParticiple: 'flown',
    translation: 'летать',
    level: 'A2',
    verbType: 'IRREGULAR',
    frequency: 6,
    difficulty: 6,
    languageCode: 'en',
    transcription: 'flaɪ',
  },
];
