import { CardDifficulty, LanguageLevel } from '@prisma/client';

export interface NounData {
  term: string;
  slug: string;
  transcription: string;
  translation: string;
  level: LanguageLevel;
  difficulty: CardDifficulty;
  frequency: number;
  languageCode: string;
}

export const nounsData: NounData[] = [
  // A1 Level - Basic Nouns
  {
    term: 'house',
    slug: 'house',
    transcription: 'haʊs',
    translation: 'дом',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'car',
    slug: 'car',
    transcription: 'kɑː',
    translation: 'машина',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'book',
    slug: 'book',
    transcription: 'bʊk',
    translation: 'книга',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'water',
    slug: 'water',
    transcription: 'ˈwɔːtə',
    translation: 'вода',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'food',
    slug: 'food',
    transcription: 'fuːd',
    translation: 'еда',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'time',
    slug: 'time',
    transcription: 'taɪm',
    translation: 'время',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'day',
    slug: 'day',
    transcription: 'deɪ',
    translation: 'день',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'night',
    slug: 'night',
    transcription: 'naɪt',
    translation: 'ночь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'year',
    slug: 'year',
    transcription: 'jɪə',
    translation: 'год',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'month',
    slug: 'month',
    transcription: 'mʌnθ',
    translation: 'месяц',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'week',
    slug: 'week',
    transcription: 'wiːk',
    translation: 'неделя',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'hour',
    slug: 'hour',
    transcription: 'ˈaʊə',
    translation: 'час',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'minute',
    slug: 'minute',
    transcription: 'ˈmɪnɪt',
    translation: 'минута',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'family',
    slug: 'family',
    transcription: 'ˈfæmɪli',
    translation: 'семья',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'friend',
    slug: 'friend',
    transcription: 'frend',
    translation: 'друг',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'mother',
    slug: 'mother',
    transcription: 'ˈmʌðə',
    translation: 'мать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'father',
    slug: 'father',
    transcription: 'ˈfɑːðə',
    translation: 'отец',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'sister',
    slug: 'sister',
    transcription: 'ˈsɪstə',
    translation: 'сестра',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'brother',
    slug: 'brother',
    transcription: 'ˈbrʌðə',
    translation: 'брат',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'child',
    slug: 'child',
    transcription: 'tʃaɪld',
    translation: 'ребенок',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'man',
    slug: 'man',
    transcription: 'mæn',
    translation: 'мужчина',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'woman',
    slug: 'woman',
    transcription: 'ˈwʊmən',
    translation: 'женщина',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'boy',
    slug: 'boy',
    transcription: 'bɔɪ',
    translation: 'мальчик',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'girl',
    slug: 'girl',
    transcription: 'ɡɜːl',
    translation: 'девочка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'teacher',
    slug: 'teacher',
    transcription: 'ˈtiːtʃə',
    translation: 'учитель',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'student',
    slug: 'student',
    transcription: 'ˈstjuːdənt',
    translation: 'студент',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'doctor',
    slug: 'doctor',
    transcription: 'ˈdɒktə',
    translation: 'врач',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'work',
    slug: 'work',
    transcription: 'wɜːk',
    translation: 'работа',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'school',
    slug: 'school',
    transcription: 'skuːl',
    translation: 'школа',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'home',
    slug: 'home',
    transcription: 'həʊm',
    translation: 'дом',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'room',
    slug: 'room',
    transcription: 'ruːm',
    translation: 'комната',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'door',
    slug: 'door',
    transcription: 'dɔː',
    translation: 'дверь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'window',
    slug: 'window',
    transcription: 'ˈwɪndəʊ',
    translation: 'окно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'table',
    slug: 'table',
    transcription: 'ˈteɪbl',
    translation: 'стол',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'chair',
    slug: 'chair',
    transcription: 'tʃeə',
    translation: 'стул',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'bed',
    slug: 'bed',
    transcription: 'bed',
    translation: 'кровать',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'phone',
    slug: 'phone',
    transcription: 'fəʊn',
    translation: 'телефон',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'computer',
    slug: 'computer',
    transcription: 'kəmˈpjuːtə',
    translation: 'компьютер',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'money',
    slug: 'money',
    transcription: 'ˈmʌni',
    translation: 'деньги',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'name',
    slug: 'name',
    transcription: 'neɪm',
    translation: 'имя',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'number',
    slug: 'number',
    transcription: 'ˈnʌmbə',
    translation: 'число',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'word',
    slug: 'word',
    transcription: 'wɜːd',
    translation: 'слово',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'question',
    slug: 'question',
    transcription: 'ˈkwestʃən',
    translation: 'вопрос',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'answer',
    slug: 'answer',
    transcription: 'ˈɑːnsə',
    translation: 'ответ',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'problem',
    slug: 'problem',
    transcription: 'ˈprɒbləm',
    translation: 'проблема',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'idea',
    slug: 'idea',
    transcription: 'aɪˈdɪə',
    translation: 'идея',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'way',
    slug: 'way',
    transcription: 'weɪ',
    translation: 'путь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'place',
    slug: 'place',
    transcription: 'pleɪs',
    translation: 'место',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'thing',
    slug: 'thing',
    transcription: 'θɪŋ',
    translation: 'вещь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'people',
    slug: 'people',
    transcription: 'ˈpiːpl',
    translation: 'люди',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'country',
    slug: 'country',
    transcription: 'ˈkʌntri',
    translation: 'страна',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'city',
    slug: 'city',
    transcription: 'ˈsɪti',
    translation: 'город',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'street',
    slug: 'street',
    transcription: 'striːt',
    translation: 'улица',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'shop',
    slug: 'shop',
    transcription: 'ʃɒp',
    translation: 'магазин',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'restaurant',
    slug: 'restaurant',
    transcription: 'ˈrestrɒnt',
    translation: 'ресторан',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'hospital',
    slug: 'hospital',
    transcription: 'ˈhɒspɪtl',
    translation: 'больница',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'bank',
    slug: 'bank',
    transcription: 'bæŋk',
    translation: 'банк',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'station',
    slug: 'station',
    transcription: 'ˈsteɪʃn',
    translation: 'станция',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'airport',
    slug: 'airport',
    transcription: 'ˈeəpɔːt',
    translation: 'аэропорт',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'hotel',
    slug: 'hotel',
    transcription: 'həʊˈtel',
    translation: 'отель',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'park',
    slug: 'park',
    transcription: 'pɑːk',
    translation: 'парк',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'beach',
    slug: 'beach',
    transcription: 'biːtʃ',
    translation: 'пляж',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'mountain',
    slug: 'mountain',
    transcription: 'ˈmaʊntən',
    translation: 'гора',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'river',
    slug: 'river',
    transcription: 'ˈrɪvə',
    translation: 'река',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'sea',
    slug: 'sea',
    transcription: 'siː',
    translation: 'море',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'sun',
    slug: 'sun',
    transcription: 'sʌn',
    translation: 'солнце',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'moon',
    slug: 'moon',
    transcription: 'muːn',
    translation: 'луна',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'star',
    slug: 'star',
    transcription: 'stɑː',
    translation: 'звезда',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'tree',
    slug: 'tree',
    transcription: 'triː',
    translation: 'дерево',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'flower',
    slug: 'flower',
    transcription: 'ˈflaʊə',
    translation: 'цветок',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'animal',
    slug: 'animal',
    transcription: 'ˈænɪml',
    translation: 'животное',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'dog',
    slug: 'dog',
    transcription: 'dɒɡ',
    translation: 'собака',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'cat',
    slug: 'cat',
    transcription: 'kæt',
    translation: 'кошка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'bird',
    slug: 'bird',
    transcription: 'bɜːd',
    translation: 'птица',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'fish',
    slug: 'fish',
    transcription: 'fɪʃ',
    translation: 'рыба',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'horse',
    slug: 'horse',
    transcription: 'hɔːs',
    translation: 'лошадь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'cow',
    slug: 'cow',
    transcription: 'kaʊ',
    translation: 'корова',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'chicken',
    slug: 'chicken',
    transcription: 'ˈtʃɪkɪn',
    translation: 'курица',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'pig',
    slug: 'pig',
    transcription: 'pɪɡ',
    translation: 'свинья',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'sheep',
    slug: 'sheep',
    transcription: 'ʃiːp',
    translation: 'овца',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'bread',
    slug: 'bread',
    transcription: 'bred',
    translation: 'хлеб',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'milk',
    slug: 'milk',
    transcription: 'mɪlk',
    translation: 'молоко',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'egg',
    slug: 'egg',
    transcription: 'eɡ',
    translation: 'яйцо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'meat',
    slug: 'meat',
    transcription: 'miːt',
    translation: 'мясо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'rice',
    slug: 'rice',
    transcription: 'raɪs',
    translation: 'рис',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'potato',
    slug: 'potato',
    transcription: 'pəˈteɪtəʊ',
    translation: 'картофель',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'tomato',
    slug: 'tomato',
    transcription: 'təˈmɑːtəʊ',
    translation: 'помидор',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'apple',
    slug: 'apple',
    transcription: 'ˈæpl',
    translation: 'яблоко',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'banana',
    slug: 'banana',
    transcription: 'bəˈnɑːnə',
    translation: 'банан',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'orange',
    slug: 'orange',
    transcription: 'ˈɒrɪndʒ',
    translation: 'апельсин',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'coffee',
    slug: 'coffee',
    transcription: 'ˈkɒfi',
    translation: 'кофе',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'tea',
    slug: 'tea',
    transcription: 'tiː',
    translation: 'чай',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'juice',
    slug: 'juice',
    transcription: 'dʒuːs',
    translation: 'сок',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'beer',
    slug: 'beer',
    transcription: 'bɪə',
    translation: 'пиво',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'wine',
    slug: 'wine',
    transcription: 'waɪn',
    translation: 'вино',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'cake',
    slug: 'cake',
    transcription: 'keɪk',
    translation: 'торт',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'chocolate',
    slug: 'chocolate',
    transcription: 'ˈtʃɒklət',
    translation: 'шоколад',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'sugar',
    slug: 'sugar',
    transcription: 'ˈʃʊɡə',
    translation: 'сахар',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'salt',
    slug: 'salt',
    transcription: 'sɔːlt',
    translation: 'соль',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'paper',
    slug: 'paper',
    transcription: 'ˈpeɪpə',
    translation: 'бумага',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'pen',
    slug: 'pen',
    transcription: 'pen',
    translation: 'ручка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'pencil',
    slug: 'pencil',
    transcription: 'ˈpensl',
    translation: 'карандаш',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'bag',
    slug: 'bag',
    transcription: 'bæɡ',
    translation: 'сумка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'shirt',
    slug: 'shirt',
    transcription: 'ʃɜːt',
    translation: 'рубашка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'shoes',
    slug: 'shoes',
    transcription: 'ʃuːz',
    translation: 'обувь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'hat',
    slug: 'hat',
    transcription: 'hæt',
    translation: 'шляпа',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'watch',
    slug: 'watch',
    transcription: 'wɒtʃ',
    translation: 'часы',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'ring',
    slug: 'ring',
    transcription: 'rɪŋ',
    translation: 'кольцо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'key',
    slug: 'key',
    transcription: 'kiː',
    translation: 'ключ',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'map',
    slug: 'map',
    transcription: 'mæp',
    translation: 'карта',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'photo',
    slug: 'photo',
    transcription: 'ˈfəʊtəʊ',
    translation: 'фото',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'picture',
    slug: 'picture',
    transcription: 'ˈpɪktʃə',
    translation: 'картина',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'film',
    slug: 'film',
    transcription: 'fɪlm',
    translation: 'фильм',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'music',
    slug: 'music',
    transcription: 'ˈmjuːzɪk',
    translation: 'музыка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'song',
    slug: 'song',
    transcription: 'sɒŋ',
    translation: 'песня',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'game',
    slug: 'game',
    transcription: 'ɡeɪm',
    translation: 'игра',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'ball',
    slug: 'ball',
    transcription: 'bɔːl',
    translation: 'мяч',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'toy',
    slug: 'toy',
    transcription: 'tɔɪ',
    translation: 'игрушка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'gift',
    slug: 'gift',
    transcription: 'ɡɪft',
    translation: 'подарок',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'party',
    slug: 'party',
    transcription: 'ˈpɑːti',
    translation: 'вечеринка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'holiday',
    slug: 'holiday',
    transcription: 'ˈhɒlɪdeɪ',
    translation: 'отпуск',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'birthday',
    slug: 'birthday',
    transcription: 'ˈbɜːθdeɪ',
    translation: 'день рождения',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'Christmas',
    slug: 'christmas',
    transcription: 'ˈkrɪsməs',
    translation: 'Рождество',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'weather',
    slug: 'weather',
    transcription: 'ˈweðə',
    translation: 'погода',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'rain',
    slug: 'rain',
    transcription: 'reɪn',
    translation: 'дождь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'snow',
    slug: 'snow',
    transcription: 'snəʊ',
    translation: 'снег',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'wind',
    slug: 'wind',
    transcription: 'wɪnd',
    translation: 'ветер',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'cloud',
    slug: 'cloud',
    transcription: 'klaʊd',
    translation: 'облако',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'sky',
    slug: 'sky',
    transcription: 'skaɪ',
    translation: 'небо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'ground',
    slug: 'ground',
    transcription: 'ɡraʊnd',
    translation: 'земля',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'floor',
    slug: 'floor',
    transcription: 'flɔː',
    translation: 'пол',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'wall',
    slug: 'wall',
    transcription: 'wɔːl',
    translation: 'стена',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'roof',
    slug: 'roof',
    transcription: 'ruːf',
    translation: 'крыша',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'stairs',
    slug: 'stairs',
    transcription: 'steəz',
    translation: 'лестница',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'lift',
    slug: 'lift',
    transcription: 'lɪft',
    translation: 'лифт',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'bus',
    slug: 'bus',
    transcription: 'bʌs',
    translation: 'автобус',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'train',
    slug: 'train',
    transcription: 'treɪn',
    translation: 'поезд',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'plane',
    slug: 'plane',
    transcription: 'pleɪn',
    translation: 'самолет',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'boat',
    slug: 'boat',
    transcription: 'bəʊt',
    translation: 'лодка',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'bike',
    slug: 'bike',
    transcription: 'baɪk',
    translation: 'велосипед',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'road',
    slug: 'road',
    transcription: 'rəʊd',
    translation: 'дорога',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'bridge',
    slug: 'bridge',
    transcription: 'brɪdʒ',
    translation: 'мост',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'light',
    slug: 'light',
    transcription: 'laɪt',
    translation: 'свет',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'fire',
    slug: 'fire',
    transcription: 'ˈfaɪə',
    translation: 'огонь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'smoke',
    slug: 'smoke',
    transcription: 'sməʊk',
    translation: 'дым',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'ice',
    slug: 'ice',
    transcription: 'aɪs',
    translation: 'лед',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'fire',
    slug: 'fire',
    transcription: 'ˈfaɪə',
    translation: 'огонь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'smoke',
    slug: 'smoke',
    transcription: 'sməʊk',
    translation: 'дым',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'ice',
    slug: 'ice',
    transcription: 'aɪs',
    translation: 'лед',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
];
