import { CardDifficulty, LanguageLevel } from '@prisma/client';

export interface PhraseData {
  term: string;
  slug: string;
  transcription: string;
  translation: string;
  level: LanguageLevel;
  difficulty: CardDifficulty;
  frequency: number;
  languageCode: string;
}

export const phrasesData: PhraseData[] = [
  // A1 Level - Basic Phrases
  {
    term: 'hello',
    slug: 'hello',
    transcription: 'həˈləʊ',
    translation: 'привет',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'goodbye',
    slug: 'goodbye',
    transcription: 'ˌɡʊdˈbaɪ',
    translation: 'до свидания',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'thank you',
    slug: 'thank-you',
    transcription: 'ˈθæŋk juː',
    translation: 'спасибо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'please',
    slug: 'please',
    transcription: 'pliːz',
    translation: 'пожалуйста',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 10,
    languageCode: 'en',
  },
  {
    term: 'excuse me',
    slug: 'excuse-me',
    transcription: 'ɪkˈskjuːz miː',
    translation: 'извините',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'sorry',
    slug: 'sorry',
    transcription: 'ˈsɒri',
    translation: 'извините',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'how are you',
    slug: 'how-are-you',
    transcription: 'haʊ ɑː juː',
    translation: 'как дела',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'I am fine',
    slug: 'i-am-fine',
    transcription: 'aɪ æm faɪn',
    translation: 'у меня все хорошо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'what is your name',
    slug: 'what-is-your-name',
    transcription: 'wɒt ɪz jɔː neɪm',
    translation: 'как вас зовут',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'my name is',
    slug: 'my-name-is',
    transcription: 'maɪ neɪm ɪz',
    translation: 'меня зовут',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'nice to meet you',
    slug: 'nice-to-meet-you',
    transcription: 'naɪs tuː miːt juː',
    translation: 'приятно познакомиться',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'where are you from',
    slug: 'where-are-you-from',
    transcription: 'weə ɑː juː frɒm',
    translation: 'откуда вы',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'I am from',
    slug: 'i-am-from',
    transcription: 'aɪ æm frɒm',
    translation: 'я из',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'how old are you',
    slug: 'how-old-are-you',
    transcription: 'haʊ əʊld ɑː juː',
    translation: 'сколько вам лет',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I am years old',
    slug: 'i-am-years-old',
    transcription: 'aɪ æm jɪəz əʊld',
    translation: 'мне лет',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'do you speak English',
    slug: 'do-you-speak-english',
    transcription: 'duː juː spiːk ˈɪŋɡlɪʃ',
    translation: 'вы говорите по-английски',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'I speak English',
    slug: 'i-speak-english',
    transcription: 'aɪ spiːk ˈɪŋɡlɪʃ',
    translation: 'я говорю по-английски',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'I do not understand',
    slug: 'i-do-not-understand',
    transcription: 'aɪ duː nɒt ˌʌndəˈstænd',
    translation: 'я не понимаю',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'can you help me',
    slug: 'can-you-help-me',
    transcription: 'kæn juː help miː',
    translation: 'можете помочь мне',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'I need help',
    slug: 'i-need-help',
    transcription: 'aɪ niːd help',
    translation: 'мне нужна помощь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'where is the bathroom',
    slug: 'where-is-the-bathroom',
    transcription: 'weə ɪz ðə ˈbɑːθruːm',
    translation: 'где туалет',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'how much is this',
    slug: 'how-much-is-this',
    transcription: 'haʊ mʌtʃ ɪz ðɪs',
    translation: 'сколько это стоит',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'it is expensive',
    slug: 'it-is-expensive',
    transcription: 'ɪt ɪz ɪkˈspensɪv',
    translation: 'это дорого',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'it is cheap',
    slug: 'it-is-cheap',
    transcription: 'ɪt ɪz tʃiːp',
    translation: 'это дешево',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I like this',
    slug: 'i-like-this',
    transcription: 'aɪ laɪk ðɪs',
    translation: 'мне это нравится',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'I do not like this',
    slug: 'i-do-not-like-this',
    transcription: 'aɪ duː nɒt laɪk ðɪs',
    translation: 'мне это не нравится',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'what time is it',
    slug: 'what-time-is-it',
    transcription: 'wɒt taɪm ɪz ɪt',
    translation: 'который час',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'it is o clock',
    slug: 'it-is-o-clock',
    transcription: 'ɪt ɪz əʊ klɒk',
    translation: 'часов',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'what is the weather like',
    slug: 'what-is-the-weather-like',
    transcription: 'wɒt ɪz ðə ˈweðə laɪk',
    translation: 'какая погода',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'it is sunny',
    slug: 'it-is-sunny',
    transcription: 'ɪt ɪz ˈsʌni',
    translation: 'солнечно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'it is raining',
    slug: 'it-is-raining',
    transcription: 'ɪt ɪz ˈreɪnɪŋ',
    translation: 'идет дождь',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'it is cold',
    slug: 'it-is-cold',
    transcription: 'ɪt ɪz kəʊld',
    translation: 'холодно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'it is hot',
    slug: 'it-is-hot',
    transcription: 'ɪt ɪz hɒt',
    translation: 'жарко',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I am hungry',
    slug: 'i-am-hungry',
    transcription: 'aɪ æm ˈhʌŋɡri',
    translation: 'я голоден',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I am thirsty',
    slug: 'i-am-thirsty',
    transcription: 'aɪ æm ˈθɜːsti',
    translation: 'я хочу пить',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'I am tired',
    slug: 'i-am-tired',
    transcription: 'aɪ æm ˈtaɪəd',
    translation: 'я устал',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I am sick',
    slug: 'i-am-sick',
    transcription: 'aɪ æm sɪk',
    translation: 'я болен',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'I am happy',
    slug: 'i-am-happy',
    transcription: 'aɪ æm ˈhæpi',
    translation: 'я счастлив',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I am sad',
    slug: 'i-am-sad',
    transcription: 'aɪ æm sæd',
    translation: 'я грустен',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'good morning',
    slug: 'good-morning',
    transcription: 'ˌɡʊd ˈmɔːnɪŋ',
    translation: 'доброе утро',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 9,
    languageCode: 'en',
  },
  {
    term: 'good afternoon',
    slug: 'good-afternoon',
    transcription: 'ˌɡʊd ˌɑːftəˈnuːn',
    translation: 'добрый день',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'good evening',
    slug: 'good-evening',
    transcription: 'ˌɡʊd ˈiːvnɪŋ',
    translation: 'добрый вечер',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'good night',
    slug: 'good-night',
    transcription: 'ˌɡʊd ˈnaɪt',
    translation: 'спокойной ночи',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'see you later',
    slug: 'see-you-later',
    transcription: 'siː juː ˈleɪtə',
    translation: 'увидимся позже',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'see you tomorrow',
    slug: 'see-you-tomorrow',
    transcription: 'siː juː təˈmɒrəʊ',
    translation: 'увидимся завтра',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'have a nice day',
    slug: 'have-a-nice-day',
    transcription: 'hæv ə naɪs deɪ',
    translation: 'хорошего дня',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'take care',
    slug: 'take-care',
    transcription: 'teɪk keə',
    translation: 'береги себя',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'no problem',
    slug: 'no-problem',
    transcription: 'nəʊ ˈprɒbləm',
    translation: 'нет проблем',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'you are welcome',
    slug: 'you-are-welcome',
    transcription: 'juː ɑː ˈwelkəm',
    translation: 'пожалуйста',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'that is okay',
    slug: 'that-is-okay',
    transcription: 'ðæt ɪz əʊˈkeɪ',
    translation: 'это нормально',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'that is fine',
    slug: 'that-is-fine',
    transcription: 'ðæt ɪz faɪn',
    translation: 'это хорошо',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I agree',
    slug: 'i-agree',
    transcription: 'aɪ əˈɡriː',
    translation: 'я согласен',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I disagree',
    slug: 'i-disagree',
    transcription: 'aɪ ˌdɪsəˈɡriː',
    translation: 'я не согласен',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'I think so',
    slug: 'i-think-so',
    transcription: 'aɪ θɪŋk səʊ',
    translation: 'я думаю да',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'I do not think so',
    slug: 'i-do-not-think-so',
    transcription: 'aɪ duː nɒt θɪŋk səʊ',
    translation: 'я не думаю',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'maybe',
    slug: 'maybe',
    transcription: 'ˈmeɪbi',
    translation: 'может быть',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'probably',
    slug: 'probably',
    transcription: 'ˈprɒbəbli',
    translation: 'вероятно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'definitely',
    slug: 'definitely',
    transcription: 'ˈdefɪnətli',
    translation: 'определенно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'of course',
    slug: 'of-course',
    transcription: 'əv kɔːs',
    translation: 'конечно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'certainly',
    slug: 'certainly',
    transcription: 'ˈsɜːtnli',
    translation: 'конечно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'absolutely',
    slug: 'absolutely',
    transcription: 'ˈæbsəluːtli',
    translation: 'абсолютно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'not at all',
    slug: 'not-at-all',
    transcription: 'nɒt æt ɔːl',
    translation: 'совсем нет',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'by the way',
    slug: 'by-the-way',
    transcription: 'baɪ ðə weɪ',
    translation: 'кстати',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'in fact',
    slug: 'in-fact',
    transcription: 'ɪn fækt',
    translation: 'на самом деле',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'actually',
    slug: 'actually',
    transcription: 'ˈæktʃuəli',
    translation: 'на самом деле',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'basically',
    slug: 'basically',
    transcription: 'ˈbeɪsɪkli',
    translation: 'в основном',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'generally',
    slug: 'generally',
    transcription: 'ˈdʒenrəli',
    translation: 'в общем',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'usually',
    slug: 'usually',
    transcription: 'ˈjuːʒuəli',
    translation: 'обычно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'sometimes',
    slug: 'sometimes',
    transcription: 'ˈsʌmtaɪmz',
    translation: 'иногда',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'never',
    slug: 'never',
    transcription: 'ˈnevə',
    translation: 'никогда',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'always',
    slug: 'always',
    transcription: 'ˈɔːlweɪz',
    translation: 'всегда',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'often',
    slug: 'often',
    transcription: 'ˈɒfn',
    translation: 'часто',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'rarely',
    slug: 'rarely',
    transcription: 'ˈreəli',
    translation: 'редко',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'almost',
    slug: 'almost',
    transcription: 'ˈɔːlməʊst',
    translation: 'почти',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'nearly',
    slug: 'nearly',
    transcription: 'ˈnɪəli',
    translation: 'почти',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'about',
    slug: 'about',
    transcription: 'əˈbaʊt',
    translation: 'около',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'approximately',
    slug: 'approximately',
    transcription: 'əˈprɒksɪmətli',
    translation: 'приблизительно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'exactly',
    slug: 'exactly',
    transcription: 'ɪɡˈzæktli',
    translation: 'точно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'precisely',
    slug: 'precisely',
    transcription: 'prɪˈsaɪsli',
    translation: 'точно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'especially',
    slug: 'especially',
    transcription: 'ɪˈspeʃəli',
    translation: 'особенно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'particularly',
    slug: 'particularly',
    transcription: 'pəˈtɪkjələli',
    translation: 'особенно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'mainly',
    slug: 'mainly',
    transcription: 'ˈmeɪnli',
    translation: 'главным образом',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'mostly',
    slug: 'mostly',
    transcription: 'ˈməʊstli',
    translation: 'в основном',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'partly',
    slug: 'partly',
    transcription: 'ˈpɑːtli',
    translation: 'частично',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'completely',
    slug: 'completely',
    transcription: 'kəmˈpliːtli',
    translation: 'полностью',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'totally',
    slug: 'totally',
    transcription: 'ˈtəʊtəli',
    translation: 'полностью',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'entirely',
    slug: 'entirely',
    transcription: 'ɪnˈtaɪəli',
    translation: 'полностью',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'almost',
    slug: 'almost',
    transcription: 'ˈɔːlməʊst',
    translation: 'почти',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 7,
    languageCode: 'en',
  },
  {
    term: 'nearly',
    slug: 'nearly',
    transcription: 'ˈnɪəli',
    translation: 'почти',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'about',
    slug: 'about',
    transcription: 'əˈbaʊt',
    translation: 'около',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 8,
    languageCode: 'en',
  },
  {
    term: 'approximately',
    slug: 'approximately',
    transcription: 'əˈprɒksɪmətli',
    translation: 'приблизительно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'exactly',
    slug: 'exactly',
    transcription: 'ɪɡˈzæktli',
    translation: 'точно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'precisely',
    slug: 'precisely',
    transcription: 'prɪˈsaɪsli',
    translation: 'точно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'especially',
    slug: 'especially',
    transcription: 'ɪˈspeʃəli',
    translation: 'особенно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'particularly',
    slug: 'particularly',
    transcription: 'pəˈtɪkjələli',
    translation: 'особенно',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'mainly',
    slug: 'mainly',
    transcription: 'ˈmeɪnli',
    translation: 'главным образом',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'mostly',
    slug: 'mostly',
    transcription: 'ˈməʊstli',
    translation: 'в основном',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'partly',
    slug: 'partly',
    transcription: 'ˈpɑːtli',
    translation: 'частично',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
  {
    term: 'completely',
    slug: 'completely',
    transcription: 'kəmˈpliːtli',
    translation: 'полностью',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'totally',
    slug: 'totally',
    transcription: 'ˈtəʊtəli',
    translation: 'полностью',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 6,
    languageCode: 'en',
  },
  {
    term: 'entirely',
    slug: 'entirely',
    transcription: 'ɪnˈtaɪəli',
    translation: 'полностью',
    level: 'A1',
    difficulty: 'EASY',
    frequency: 5,
    languageCode: 'en',
  },
];
